package com.example.InstagramDemo.Database_files;

import android.provider.BaseColumns;

public class PostContractor {

    public static final class FeedPost implements BaseColumns {
//_ID is automatically generated by basecolumns class

        public static final String TABLE_NAME = "feed";
        public static final String COLUMN_DESC = "feedDesc";
        public static final String COLUMN_IMAGE_PATH="feedImagePath";

    }

}
